name: York admin bot CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t york-admin-bot -f Dockerfile .
      - name: Tags
        run: |
          docker tag york-admin-bot ${{ secrets.DOCKER_USER }}/york-admin-bot:${{ github.sha }}
          docker tag york-admin-bot ${{ secrets.DOCKER_USER }}/york-admin-bot:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/york-admin-bot:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/york-admin-bot:latest
